# Generated by Django 5.1.3 on 2025-06-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='userquery',
            table='user_query',
        ),
    ]
